FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv \
    openocd \
    libusb-1.0-0-dev \
    usbutils \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

CMD ["bash"]
